version: '3.6'

services:
    backend: 
        build:
            context: ./PolyclinicsSystemBackend
            dockerfile: ./Dockerfile
        ports:
            - 5000:80
        container_name: backend
        restart: on-failure
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
        networks: 
            - localnetwork
        depends_on:
            - database    

    frontend:
        build:
            context: ./PolyclinicsFrontEnd
            dockerfile: ./Dockerfile
        ports:
            - 4200:4200
        container_name: frontend
        restart: on-failure
        networks: 
            - localnetwork
        volumes:
            - './PolyclinicsFrontEnd/:/usr/src/app/:rw'
            - '/usr/src/app/node_modules'
        depends_on: 
            - backend
            
    database:
        image: postgres:latest
        container_name: database
        environment: 
            - POSTGRES_DB=polyclinicsdb
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432
        networks:
            - localnetwork                    

networks: 
    localnetwork:
        driver: bridge
